---

- name: Importando la clave pública del repositorio
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: Añadiendo el repositorio
  apt_repository:
    repo: "deb https://packages.grafana.com/oss/deb stable main"
    filename: grafana
    state: present
    mode: 0644
    update_cache: yes

- name: Instalando el servicio
  apt:
    force_apt_get: yes
    update_cache: yes
    name: grafana
    state: present

- name: Habilitando e iniciando el servicio
  systemd:
    name: grafana-server
    enabled: yes

- name: Comprobando si ya existe un backup de la configuración
  stat:
    path: /etc/grafana/grafana.ini_original
  register: bk_grafana

- name: Haciendo un backup de la configuración
  copy:
    src: /etc/grafana/grafana.ini
    remote_src: yes
    dest: /etc/grafana/grafana.ini_original
    owner: root
    group: root
    mode: 0640
  when: not bk_grafana['stat']['exists']

- name: Creando el directorio de los certificados para Grafana
  file:
    path: /etc/grafana/ssl/
    state: directory
    owner: root
    group: grafana
    mode: 0750

- name: Copiando los certificados que usará Grafana
  copy:
    src: "{{ item.src }}"
    remote_src: no
    dest: "{{ item.dest }}"
    owner: root
    group: grafana
    mode: 0640
  with_items:
    - src: "{{ site_cert_file }}"
      dest: "/etc/grafana/ssl/{{ site_cert_file }}"
    - src: "{{ site_cert_key }}"
      dest: "/etc/grafana/ssl/{{ site_cert_key }}"

- name: Customizando la configuración del servicio
  replace:
    path: /etc/grafana/grafana.ini
    regexp: "{{ item.key }}"
    replace: "{{ item.value }}"
  with_items:
    - { key: '^;?app_mode =.*', value: 'app_mode = production' }
    - { key: '^;?instance_name =', value: 'instance_name =' }
    ## [paths] section
    - { key: '^;data =', value: 'data =' }
    - { key: '^;?temp_data_lifetime =', value: 'temp_data_lifetime =' }
    - { key: '^;logs =', value: 'logs =' }
    - { key: '^;?plugins =', value: 'plugins =' }
    - { key: '^;?provisioning =.*', value: 'provisioning = /etc/grafana/provisioning' }
    ## [server] section
    - { key: '^;?protocol =.*', value: 'protocol = https' }
    - { key: '^;?http_port =.*', value: "http_port = {{ grafana_port }}" }
    - { key: '^;?domain =.*', value: "domain = {{ site_domain }}" }
    - { key: '^;?router_logging = false', value: 'router_logging = false' }
    - { key: '^;?x_xss_protection =.*', value: 'x_xss_protection = true' }
    ## [dashboard] section
    - { key: '^;?versions_to_keep =.*', value: 'versions_to_keep = 3' }
    ## [users] section
    - { key: '^;?allow_sign_up =.*', value: 'allow_sign_up = false' }
    - { key: '^;?allow_org_create =.*', value: 'allow_org_create = false' }
    - { key: '^;?auto_assign_org_role =.*', value: 'auto_assign_org_role = Viewer' }
    - { key: '^;?viewers_can_edit =.*', value: 'viewers_can_edit = false' }
    - { key: '^;?viewers_can_admin =.*', value: 'viewers_can_admin = false' }
    ## [auth] section
    - { key: '^;?login_cookie_name =.*', value: 'login_cookie_name = grafana_session' }
    - { key: '^;?login_maximum_inactive_lifetime_days =.*', value: 'login_maximum_inactive_lifetime_days = 1' }
    - { key: '^;?login_maximum_lifetime_days =.*', value: 'login_maximum_lifetime_days = 1' }
    ## [log] section
    - { key: '^;?mode =.*', value: 'mode = console file' }
    - { key: '^;?log_rotate =.*', value: 'log_rotate = true' }
    - { key: '^;?daily_rotate =.*', value: 'daily_rotate = true' }
    - { key: '^;?max_days = 7', value: "max_days = {{ grafana_log_rotation }}" }
  notify: grafana restart

- name: Terminando de customizar la configuración del servicio
  replace:
    path: /etc/grafana/grafana.ini
    regexp: "{{ item.match }}"
    replace: "{{ item.value }}"
  with_items:
    ## [auth.*] sections
    - { match: '^# enable anonymous access\n^;?enabled =.*', value: '# enable anonymous access\nenabled = false' }
    - { match: '^\[auth\.github\]\n^;?enabled =.*', value: '[auth.github]\nenabled = false' }
    - { match: '^\[auth\.gitlab\]\n^;?enabled =.*', value: '[auth.gitlab]\nenabled = false' }
    - { match: '^\[auth\.google\]\n^;?enabled =.*', value: '[auth.google]\nenabled = false' }
    - { match: '^\[auth\.grafana_com\]\n^;?enabled =.*', value: '[auth.grafana_com]\nenabled = false' }
    - { match: '^;?name = Azure AD\n^;?enabled =.*', value: ';name = Azure AD\nenabled = false' }
    - { match: '^;?name = Okta\n^;?enabled =.*', value: ';name = Okta\nenabled = false' }
    - { match: '^\[auth\.generic_oauth\]\n^;?enabled =.*', value: '[auth.generic_oauth]\nenabled = false' }
    - { match: '^\[auth\.basic\]\n^;?enabled =.*', value: '[auth.basic]\nenabled = true' }
    - { match: '^\[auth\.proxy\]\n^;?enabled =.*', value: '[auth.proxy]\nenabled = false' }
    - { match: '^\[auth\.ldap\]\n^;?enabled =.*', value: '[auth.ldap]\nenabled = false' }
    ## [smtp] section
    - { match: '^\[smtp\]\n^;?enabled =.*', value: '[smtp]\nenabled = false' }
    ## [log] section
    - match: '^# Either "debug", "info", "warn", "error", "critical", default is "info"\n^;?level =.*'
      value: '# Either "debug", "info", "warn", "error", "critical", default is "info"\nlevel = info'
  notify: grafana restart

- name: Habilitando el firewall
  ufw:
    rule: allow
    port: "{{ grafana_port | string }}"
    proto: tcp
    comment: "Allowing Grafana"

- name: Creando el directorio de los dashboards
  file:
    path: /var/lib/grafana/dashboards
    owner: grafana
    group: grafana
    mode: 0750
    state: directory

- name: Copiando el datasource y el dashboard para Icinga2
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: grafana
    mode: 0640
  with_items:
    - { src: 'datasource_icinga2.j2', dest: '/etc/grafana/provisioning/datasources/datasource-icinga2.yaml' }
    - { src: 'dashboard_icinga2.j2', dest: '/etc/grafana/provisioning/dashboards/dashboard-icinga2.yaml' }
  notify: grafana restart

- name: Copiando el dashboard para Icinga2
  copy:
    src: dashboad_icinga2.json
    dest: /var/lib/grafana/dashboards/dashboard_icinga2.json
    owner: grafana
    group: grafana
    mode: 0640

...
