---

- name: Ejecutando molecule coverge
  hosts: all
  become: true
  become_method: sudo
  vars:
    ssh_port: 22

  tasks:
    - name: Incluyendo el rol 'influxdb'
      include_role:
        name: 'influxdb'

...
