---

- name: Ejecutando molecule coverge
  hosts: all
  become: true
  become_method: sudo
  tasks:
    - name: Incluyendo el rol 'mariadb_hardening'
      include_role:
        name: 'mariadb_hardening'

...
