---

- name: Comprobando la variable 'db_root_password'
  fail:
    msg: "Tienes que establecer la contraseña en la variable 'db_root_password'. Revisa el README del rol."
  when: db_root_password == ''

- name: Instalando MariaDB
  apt:
    force_apt_get: yes
    update_cache: yes
    name:
      - mariadb-server
      - mariadb-client
      - python3-mysqldb
    state: latest

- name: Iniciando y habilitando el servicio
  systemd:
    name: mariadb
    enabled: yes
    state: started

- name: Comprobando el acceso sin contraseña
  command: |
    mysqladmin -u root version
  register: root_login
  ignore_errors: true
  no_log: true

- name: Estableciendo la contraseña del usuario 'root'
  mysql_user:
    name: root
    state: present
    host: localhost
    password: "{{ db_root_password }}"
    connect_timeout: 30
  no_log: true
  when: root_login is not failed

- name: Añadiendo una regla al firewall
  ufw:
    rule: allow
    port: '3306'
    proto: tcp
    direction: in
    comment: Permitiendo MariaDB

- name: Mensaje de fin del rol
  debug:
    msg: "Rol ejecutado con éxito."

...
