---

- name: Instalando Icingaweb2
  apt:
    name:
      - icingaweb2
      - icingacli
    state: latest
    force_apt_get: yes
    update_cache: yes

- name: Creando la base de datos de Icingaweb2
  mysql_db:
    login_user: "{{ db_user }}"
    login_password: "{{ db_user_password }}"
    login_host: localhost
    name: "{{ db_icingaweb2 }}"
    state: present
  no_log: true
  register: db_creation

- name: Creando el usuario para la base de datos
  mysql_user:
    login_user: "{{ db_user }}"
    login_password: "{{ db_user_password }}"
    login_host: localhost
    name: "{{ db_icingaweb2_user }}"
    password: "{{ db_icingaweb2_user_password }}"
    priv: "{{ db_icingaweb2 }}.*:ALL/*.*:SHOW DATABASES"
  no_log: true

- name: Importando la base de datos de Icingaweb2
  mysql_db:
    login_user: "{{ db_icingaweb2_user }}"
    login_password: "{{ db_icingaweb2_user_password }}"
    login_host: localhost
    name: "{{ db_icingaweb2 }}"
    state: import
    target: /usr/share/icingaweb2/etc/schema/mysql.schema.sql
  register: db_import

- name: Creando el usuario de la GUI de Icingaweb2
  command: |
    mysql -u {{ db_icingaweb2_user }} -p'{{ db_icingaweb2_user_password }}' {{ db_icingaweb2 }} -e "INSERT INTO icingaweb_user (name, active, password_hash) VALUES ('{{ icingaweb2_user }}',1,'{{ icingaweb2_user_password }}');"
  no_log: true
  when: db_import is changed

- name: Creando el directorio de configuración
  command: icingacli setup config directory
  when: db_import is changed

- name: Creando los directorios de configuración del módulo de Icingaweb2
  file:
    path: "{{ item.dir }}"
    state: directory
    recurse: yes
    owner: root
    group: icingaweb2
    mode: 0750
  with_items:
    - { dir: '/etc/icingaweb2/modules/monitoring/' }
    - { dir: '/etc/icingaweb2/enabledModules/' }

- name: Copiando la configuración de Icingaweb2
  template:
    src: "{{ item.file }}"
    dest: "{{ item.dest }}"
    mode: 0660
    owner: root
    group: icingaweb2
  with_items:
    - { file: 'config.j2', dest: '/etc/icingaweb2/config.ini' }
    - { file: 'resources.j2', dest: '/etc/icingaweb2/resources.ini' }
    - { file: 'roles.j2', dest: '/etc/icingaweb2/roles.ini' }
    - { file: 'authentication.j2', dest: '/etc/icingaweb2/authentication.ini' }
    - { file: 'module_config.j2', dest: '/etc/icingaweb2/modules/monitoring/config.ini' }
    - { file: 'module_backends.j2', dest: '/etc/icingaweb2/modules/monitoring/backends.ini' }
    - { file: 'module_commandtransports.j2', dest: '/etc/icingaweb2/modules/monitoring/commandtransports.ini' }
    - { file: 'groups.j2', dest: '/etc/icingaweb2/groups.ini' }
  notify: icinga2 restart

- name: Creando un link simbólico para el módulo de monitorización
  file:
    src: /usr/share/icingaweb2/modules/monitoring
    dest: /etc/icingaweb2/enabledModules/monitoring
    state: link

- name: Cambiando el nombre del recurso de Icinga2
  replace:
    path: /etc/icingaweb2/modules/monitoring/backends.ini
    regexp: 'resource =.*'
    replace: 'resource = "icinga2"'

- name: Copiando el virtualhost customizado
  template:
    src: virtualhost.j2
    dest: "/etc/apache2/sites-available/https-{{ site_short_name }}.conf"
    owner: root
    group: root
    mode: 0644
  notify: apache restart

...
