---

dependency:
  name: galaxy

driver:
  name: vagrant
  provider:
    name: virtualbox

lint: |
  set -e
    yamllint .
    ansible-lint

platforms:
  - name: molecule-grafana
    box: geerlingguy/ubuntu2004

provisioner:
  name: ansible

verifier:
  name: ansible

...
