---

dependency:
  name: galaxy

driver:
  name: vagrant
  provider:
    name: virtualbox

lint: |
 set -e
   yamllint .
   ansible-lint

platforms:
  - name: molecule-icingaweb
    box: geerlingguy/ubuntu2004

provisioner:
  name: ansible

verifier:
  name: ansible

...
